### ISSUE TITLE
Be able to specify threads with when using LAST

### ISSUE THREAD

**Issue by JustinChu** [bcgsc/NanoSim#1]
I'm running the read_analyis.py tool, but I'm finding the LAST alignment quite slow. I'm pretty sure LAST can be threaded and this should be an option.

**Comment by cheny19** [comment]
Users can use LAST to run alignment by themselves and provide that as an input of read_analysis.py. So I'll leave that as it is for now.

**Comment by claczny** [comment]
For the record, the option in `last` to use multiple threads is `-P`.

I decided to simply add `-P 20` to the `read_analysis.py` file at line 121 of NanoSim-1.2.0.
This becomes then:
```
call("lastal -P 20 -a 1 ref_genome " + in_fasta + " | grep '^s ' > " + out_maf, shell=True)
```

A bit hacky, but serves my purpose for now.
