### ISSUE TITLE
Invalid FASTQ records 

### ISSUE THREAD

**Issue by agshumate** [bcgsc/NanoSim#115]
Hi,
I have been using NanoSim to generate some direct RNA reads. The reads were simulated successfully but some of the reads have quality strings that are not the same length as the sequence. For example

```
@rna17262_65_aligned_45303_F_60_53_62
GGCATCTGAGAATCGGATCAAGCTTTTTTCTCGCGACGAAACACTAACTGATCTCACTATTGACATGGATTATAACTGTACTTGATGGAGCACAGTTATAATAGCTGCTTTAGCCAGTCACCTCTTTACACAAAGACTGCAACTTGTGTACGTTTCGCAGACACCGTGGACTGCT
+
))**&&/+(%0)%&.,,+-(*%+0(.('%'&/(-'/*1#-'&*$+-''%+&&++$-$1)*,'%,'*'&0%)%4&/)-','-%2-*-,))+'-$*'),4)*%'++).3*-./',&'()$%('3+%3&*$*)&.)(30+$+$''*%.*3+$2'$$'-6,&+,#&---9)6*/&,(2+*+*#+3''#'&*#$%&
```

Here is my command: 

ref_g GRCh38.fa
ref_t hg38c_protein_and_lncRNA_sorted.fa
exp hg38_stranded_spacer.tpm
model_prefix training
out simulated_dRNA
number 100000
perfect False
kmer_bias None
basecaller guppy
read_type dRNA
model_ir True
dna_type transcriptome
strandness None
max_len inf
min_len 50
uracil False
polya None
fastq True
num_threads 1
2021-03-23 14:57:33: /home/ashumate/miniconda/envs/myenv/bin/simulator.py transcriptome -rt hg38c_protein_and_lncRNA_sorted.fa -rg GRCh38.fa -e hg38_stranded_spacer.tpm -r dRNA -n 100000 --fastq -o simulated_dRNA -b guppy -c training

**Comment by cheny19** [comment]
Hi @agshumate,

Sorry for the late reply.

This was a bug in previous versions. Could you clone the Github repo to use the current version and see if this problem persists?

Thanks,
Chen

**Comment by agshumate** [comment]
Thanks Chen. I actually just proceeded using a FASTA version of the reads, so I'll close this issue now.
