### ISSUE TITLE
Error occur during read_analysis.py command running

### ISSUE THREAD

**Issue by aman21392** [bcgsc/NanoSim#121]
I used following command and it gives error please can resolve this issue as soon as possible:
 /home/aclab/apps/NanoSim/src/read_analysis.py transcriptome -i /Drive7/20200316_1633_MN33429_FAM96501_e0563569/fastq_pass/control_T.fastq -rt /Drive4/Homo_cdna.fa -rg /Drive1/human_index/Homo_sapiens.GRCh38.dna.toplevel.fa -a minimap2 --no_intron_retention -o ./transcript/control -t 70

 File "/home/aclab/apps/NanoSim/src/read_analysis.py", line 713, in <module>
    main()
  File "/home/aclab/apps/NanoSim/src/read_analysis.py", line 660, in main
    align_transcriptome(in_fasta, prefix, aligner, num_threads, t_alnm, ref_t, g_alnm, ref_g)
  File "/home/aclab/apps/NanoSim/src/read_analysis.py", line 131, in align_transcriptome
    get_primary_sam.primary_and_unaligned(g_alnm, prefix + "_genome")
  File "/home/aclab/apps/NanoSim/src/get_primary_sam.py", line 89, in primary_and_unaligned
    in_sam_file = pysam.AlignmentFile(sam_alnm_file, 'r')
  File "pysam/libcalignmentfile.pyx", line 737, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 986, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False

Thanks in advance

**Comment by cheny19** [comment]
Hi @aman21392 ,

I just tried your commands and produced no error. Could you show me the log info before this error? It looks like your alignment is not done properly due to certain reasons.

Cheers,
Chen

**Comment by aman21392** [comment]
Thanks for your reply. Here I send you  the whole log info with error:

running the code with following parameters:

infile /Drive7/2nd_nanopore_experiment_data/control_25march/20200316_1633_MN33429_FAM96501_e0563569/fastq_pass/control_T.fastq
ref_g /Drive1/human_index/Homo_sapiens.GRCh38.dna.toplevel.fa
ref_t /Drive4/nanopore_2nd_experiment/ncRNA_cdna/Homo_cdna.fa
annot 
aligner minimap2
g_alnm 
t_alnm 
prefix ./transcript/
num_threads 70
model_fit True
intron_retention False
2021-05-30 12:50:56: Read pre-process and unaligned reads analysis
2021-05-30 12:51:05: Alignment with minimap2 to reference transcriptome
[M::mm_idx_gen::7.816*1.56] collected minimizers
[M::mm_idx_gen::8.966*3.28] sorted minimizers
[M::main::9.007*3.27] loaded/built the index for 250156 target sequence(s)
[M::mm_mapopt_update::9.518*3.15] mid_occ = 142
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 250156
[M::mm_idx_stat::9.745*3.10] distinct minimizers: 19770498 (41.38% are singletons); average occurrences: 3.693; average spacing: 5.405; total length: 394654324
[M::worker_pipeline::17.290*8.45] mapped 834111 sequences
[M::worker_pipeline::27.124*5.75] mapped 258720 sequences
[M::main] Version: 2.17-r974-dirty
[M::main] CMD: minimap2 --cs -ax map-ont -t 70 /Drive4/nanopore_2nd_experiment/ncRNA_cdna/Homo_cdna.fa ./transcript/_processed.fasta
[M::main] Real time: 27.366 sec; CPU: 156.142 sec; Peak RSS: 4.201 GB
2021-05-30 12:51:33: Alignment with minimap2 to reference genome
[M::mm_idx_gen::61.017*2.05] collected minimizers
[M::mm_idx_gen::70.627*5.51] sorted minimizers
[WARNING][1;31m For a multi-part index, no @SQ lines will be outputted. Please use --split-prefix.[0m
[M::main::70.627*5.51] loaded/built the index for 32 target sequence(s)
[M::mm_mapopt_update::73.863*5.31] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 32
[M::mm_idx_stat::76.060*5.19] distinct minimizers: 167209768 (35.26% are singletons); average occurrences: 6.077; average spacing: 4.056; total length: 4121620856
[M::worker_pipeline::105.132*17.54] mapped 834111 sequences
[M::worker_pipeline::107.015*17.25] mapped 258720 sequences
[M::mm_idx_gen::126.460*14.85] collected minimizers
[M::mm_idx_gen::126.561*14.86] sorted minimizers
[M::main::126.561*14.86] loaded/built the index for 34 target sequence(s)
[M::mm_mapopt_update::126.561*14.86] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 34
[M::mm_idx_stat::126.708*14.84] distinct minimizers: 7040057 (63.57% are singletons); average occurrences: 2.114; average spacing: 274.178; total length: 4080473644
[M::worker_pipeline::142.148*19.34] mapped 834111 sequences
[M::worker_pipeline::143.740*19.16] mapped 258720 sequences
[M::mm_idx_gen::163.924*17.00] collected minimizers
[M::mm_idx_gen::163.965*17.00] sorted minimizers
[M::main::163.965*17.00] loaded/built the index for 27 target sequence(s)
[M::mm_mapopt_update::163.965*17.00] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 27
[M::mm_idx_stat::164.005*17.00] distinct minimizers: 3009320 (86.11% are singletons); average occurrences: 1.411; average spacing: 951.971; total length: 4042722680
[M::worker_pipeline::191.218*22.41] mapped 834111 sequences
[M::worker_pipeline::199.235*21.55] mapped 258720 sequences
[M::mm_idx_gen::218.759*19.76] collected minimizers
[M::mm_idx_gen::218.801*19.76] sorted minimizers
[M::main::218.801*19.76] loaded/built the index for 27 target sequence(s)
[M::mm_mapopt_update::218.801*19.76] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 27
[M::mm_idx_stat::218.838*19.76] distinct minimizers: 2422899 (88.08% are singletons); average occurrences: 1.371; average spacing: 1218.746; total length: 4047825866
[M::worker_pipeline::234.221*22.29] mapped 834111 sequences
[M::worker_pipeline::235.318*22.21] mapped 258720 sequences
[M::mm_idx_gen::254.545*20.65] collected minimizers
[M::mm_idx_gen::254.593*20.65] sorted minimizers
[M::main::254.593*20.65] loaded/built the index for 30 target sequence(s)
[M::mm_mapopt_update::254.593*20.65] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 30
[M::mm_idx_stat::254.635*20.64] distinct minimizers: 2201523 (87.94% are singletons); average occurrences: 1.360; average spacing: 1360.239; total length: 4071164743
[M::worker_pipeline::269.848*22.62] mapped 834111 sequences
[M::worker_pipeline::273.217*22.35] mapped 258720 sequences
[M::mm_idx_gen::293.841*20.89] collected minimizers
[M::mm_idx_gen::293.878*20.89] sorted minimizers
[M::main::293.878*20.89] loaded/built the index for 31 target sequence(s)
[M::mm_mapopt_update::293.878*20.89] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 31
[M::mm_idx_stat::293.914*20.89] distinct minimizers: 2127784 (92.47% are singletons); average occurrences: 1.243; average spacing: 1519.365; total length: 4019781606
[M::worker_pipeline::306.372*22.34] mapped 834111 sequences
[M::worker_pipeline::307.879*22.23] mapped 258720 sequences
[M::mm_idx_gen::327.820*20.97] collected minimizers
[M::mm_idx_gen::327.854*20.98] sorted minimizers
[M::main::327.854*20.98] loaded/built the index for 28 target sequence(s)
[M::mm_mapopt_update::327.854*20.98] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 28
[M::mm_idx_stat::327.875*20.97] distinct minimizers: 1353674 (86.80% are singletons); average occurrences: 1.500; average spacing: 1985.247; total length: 4032155065
[M::worker_pipeline::339.283*22.01] mapped 834111 sequences
[M::worker_pipeline::339.886*21.97] mapped 258720 sequences
[M::mm_idx_gen::360.922*20.78] collected minimizers
[M::mm_idx_gen::360.953*20.78] sorted minimizers
[M::main::360.953*20.78] loaded/built the index for 34 target sequence(s)
[M::mm_mapopt_update::360.953*20.78] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 34
[M::mm_idx_stat::360.972*20.78] distinct minimizers: 1490499 (90.78% are singletons); average occurrences: 1.483; average spacing: 1884.499; total length: 4166517919
[M::worker_pipeline::371.757*21.68] mapped 834111 sequences
[M::worker_pipeline::372.388*21.65] mapped 258720 sequences
[M::mm_idx_gen::392.460*20.62] collected minimizers
[M::mm_idx_gen::392.491*20.62] sorted minimizers
[M::main::392.491*20.62] loaded/built the index for 28 target sequence(s)
[M::mm_mapopt_update::392.491*20.62] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 28
[M::mm_idx_stat::392.511*20.62] distinct minimizers: 1371016 (90.53% are singletons); average occurrences: 1.245; average spacing: 2354.402; total length: 4017895798
[M::worker_pipeline::403.400*21.36] mapped 834111 sequences
[M::worker_pipeline::408.492*21.11] mapped 258720 sequences
[M::mm_idx_gen::428.207*20.21] collected minimizers
[M::mm_idx_gen::428.238*20.21] sorted minimizers
[M::main::428.238*20.21] loaded/built the index for 36 target sequence(s)
[M::mm_mapopt_update::428.238*20.21] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 36
[M::mm_idx_stat::428.258*20.21] distinct minimizers: 1137515 (88.41% are singletons); average occurrences: 1.828; average spacing: 2000.733; total length: 4160490061
[M::worker_pipeline::438.706*21.02] mapped 834111 sequences
[M::worker_pipeline::439.212*21.00] mapped 258720 sequences
[M::mm_idx_gen::459.010*20.16] collected minimizers
[M::mm_idx_gen::459.039*20.16] sorted minimizers
[M::main::459.039*20.16] loaded/built the index for 29 target sequence(s)
[M::mm_mapopt_update::459.039*20.16] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 29
[M::mm_idx_stat::459.060*20.16] distinct minimizers: 971232 (74.54% are singletons); average occurrences: 1.641; average spacing: 2518.335; total length: 4014818016
[M::worker_pipeline::467.962*20.70] mapped 834111 sequences
[M::worker_pipeline::468.514*20.68] mapped 258720 sequences
[M::mm_idx_gen::489.013*19.87] collected minimizers
[M::mm_idx_gen::489.041*19.88] sorted minimizers
[M::main::489.041*19.88] loaded/built the index for 29 target sequence(s)
[M::mm_mapopt_update::489.041*19.88] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 29
[M::mm_idx_stat::489.060*19.88] distinct minimizers: 1085952 (89.39% are singletons); average occurrences: 1.334; average spacing: 2764.143; total length: 4004787517
[M::worker_pipeline::498.833*20.51] mapped 834111 sequences
[M::worker_pipeline::499.257*20.49] mapped 258720 sequences
[M::mm_idx_gen::518.744*19.78] collected minimizers
[M::mm_idx_gen::518.773*19.78] sorted minimizers
[M::main::518.773*19.78] loaded/built the index for 25 target sequence(s)
[M::mm_mapopt_update::518.773*19.78] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 25
[M::mm_idx_stat::518.792*19.78] distinct minimizers: 903622 (91.47% are singletons); average occurrences: 1.210; average spacing: 3717.716; total length: 4065292668
[M::worker_pipeline::526.311*20.20] mapped 834111 sequences
[M::worker_pipeline::527.878*20.14] mapped 258720 sequences
[M::mm_idx_gen::547.654*19.47] collected minimizers
[M::mm_idx_gen::547.683*19.47] sorted minimizers
[M::main::547.683*19.47] loaded/built the index for 31 target sequence(s)
[M::mm_mapopt_update::547.683*19.47] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 31
[M::mm_idx_stat::547.700*19.47] distinct minimizers: 876617 (88.45% are singletons); average occurrences: 1.273; average spacing: 3650.923; total length: 4075269801
[M::worker_pipeline::555.214*19.89] mapped 834111 sequences
[M::worker_pipeline::555.561*19.88] mapped 258720 sequences
[M::mm_idx_gen::575.746*19.24] collected minimizers
[M::mm_idx_gen::575.771*19.24] sorted minimizers
[M::main::575.771*19.24] loaded/built the index for 33 target sequence(s)
[M::mm_mapopt_update::575.771*19.24] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 33
[M::mm_idx_stat::575.783*19.24] distinct minimizers: 663392 (92.63% are singletons); average occurrences: 1.221; average spacing: 5005.300; total length: 4053747445
[M::worker_pipeline::581.833*19.52] mapped 834111 sequences
[M::worker_pipeline::582.143*19.51] mapped 258720 sequences
[M::mm_idx_gen::593.021*19.18] collected minimizers
[M::mm_idx_gen::593.057*19.18] sorted minimizers
[M::main::593.057*19.18] loaded/built the index for 185 target sequence(s)
[M::mm_mapopt_update::593.057*19.18] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 185
[M::mm_idx_stat::593.097*19.18] distinct minimizers: 1792209 (66.14% are singletons); average occurrences: 2.181; average spacing: 555.888; total length: 2172634063
[M::worker_pipeline::618.728*20.42] mapped 834111 sequences
[M::worker_pipeline::628.311*20.12] mapped 258720 sequences
[M::main] Version: 2.17-r974-dirty
[M::main] CMD: minimap2 --cs -ax splice -t 70 /Drive1/human_index/Homo_sapiens.GRCh38.dna.toplevel.fa ./transcript/_processed.fasta
[M::main] Real time: 628.541 sec; CPU: 12641.425 sec; Peak RSS: 34.554 GB
2021-05-30 13:02:02: Processing transcriptome alignment file: sam
2021-05-30 13:02:06: Processing genome alignment file: sam
Traceback (most recent call last):
  File "/home/aclab/apps/NanoSim/src/read_analysis.py", line 713, in <module>
    main()
  File "/home/aclab/apps/NanoSim/src/read_analysis.py", line 660, in main
    align_transcriptome(in_fasta, prefix, aligner, num_threads, t_alnm, ref_t, g_alnm, ref_g)
  File "/home/aclab/apps/NanoSim/src/read_analysis.py", line 131, in align_transcriptome
    get_primary_sam.primary_and_unaligned(g_alnm, prefix + "_genome")
  File "/home/aclab/apps/NanoSim/src/get_primary_sam.py", line 89, in primary_and_unaligned
    in_sam_file = pysam.AlignmentFile(sam_alnm_file, 'r')
  File "pysam/libcalignmentfile.pyx", line 737, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 986, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False

running the code with following parameters:

infile /Drive7/2nd_nanopore_experiment_data/control_25march/20200316_1633_MN33429_FAM96501_e0563569/fastq_pass/control_T.fastq
ref_g /Drive1/human_index/Homo_sapiens.GRCh38.dna.toplevel.fa
ref_t /Drive4/nanopore_2nd_experiment/ncRNA_cdna/Homo_cdna.fa
annot 
aligner minimap2
g_alnm 
t_alnm 
prefix ./transcript/control
num_threads 70
model_fit True
intron_retention False
2021-05-30 13:21:18: Read pre-process and unaligned reads analysis
2021-05-30 13:21:27: Alignment with minimap2 to reference transcriptome
[M::mm_idx_gen::7.586*1.52] collected minimizers
[M::mm_idx_gen::8.223*2.95] sorted minimizers
[M::main::8.258*2.94] loaded/built the index for 250156 target sequence(s)
[M::mm_mapopt_update::8.773*2.82] mid_occ = 142
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 250156
[M::mm_idx_stat::9.006*2.78] distinct minimizers: 19770498 (41.38% are singletons); average occurrences: 3.693; average spacing: 5.405; total length: 394654324
[M::worker_pipeline::16.009*8.71] mapped 834111 sequences
[M::worker_pipeline::25.984*5.75] mapped 258720 sequences
[M::main] Version: 2.17-r974-dirty
[M::main] CMD: minimap2 --cs -ax map-ont -t 70 /Drive4/nanopore_2nd_experiment/ncRNA_cdna/Homo_cdna.fa ./transcript/control_processed.fasta
[M::main] Real time: 26.227 sec; CPU: 149.661 sec; Peak RSS: 4.148 GB
2021-05-30 13:21:53: Alignment with minimap2 to reference genome
[M::mm_idx_gen::62.740*2.03] collected minimizers
[M::mm_idx_gen::72.633*5.44] sorted minimizers
[WARNING][1;31m For a multi-part index, no @SQ lines will be outputted. Please use --split-prefix.[0m
[M::main::72.633*5.44] loaded/built the index for 32 target sequence(s)
[M::mm_mapopt_update::76.904*5.19] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 32
[M::mm_idx_stat::79.174*5.07] distinct minimizers: 167209768 (35.26% are singletons); average occurrences: 6.077; average spacing: 4.056; total length: 4121620856
[M::worker_pipeline::105.070*16.82] mapped 834111 sequences
[M::worker_pipeline::108.245*16.36] mapped 258720 sequences
[M::mm_idx_gen::128.166*14.06] collected minimizers
[M::mm_idx_gen::128.267*14.08] sorted minimizers
[M::main::128.267*14.08] loaded/built the index for 34 target sequence(s)
[M::mm_mapopt_update::128.267*14.08] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 34
[M::mm_idx_stat::128.417*14.06] distinct minimizers: 7040057 (63.57% are singletons); average occurrences: 2.114; average spacing: 274.178; total length: 4080473644
[M::worker_pipeline::143.800*18.45] mapped 834111 sequences
[M::worker_pipeline::145.159*18.29] mapped 258720 sequences
[M::mm_idx_gen::164.960*16.28] collected minimizers
[M::mm_idx_gen::164.998*16.29] sorted minimizers
[M::main::164.998*16.29] loaded/built the index for 27 target sequence(s)
[M::mm_mapopt_update::164.998*16.29] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 27
[M::mm_idx_stat::165.039*16.28] distinct minimizers: 3009320 (86.11% are singletons); average occurrences: 1.411; average spacing: 951.971; total length: 4042722680
[M::worker_pipeline::191.420*21.52] mapped 834111 sequences
[M::worker_pipeline::198.973*20.74] mapped 258720 sequences
[M::mm_idx_gen::219.532*18.94] collected minimizers
[M::mm_idx_gen::219.569*18.94] sorted minimizers
[M::main::219.569*18.94] loaded/built the index for 27 target sequence(s)
[M::mm_mapopt_update::219.569*18.94] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 27
[M::mm_idx_stat::219.606*18.94] distinct minimizers: 2422899 (88.08% are singletons); average occurrences: 1.371; average spacing: 1218.746; total length: 4047825866
[M::worker_pipeline::235.782*21.38] mapped 834111 sequences
[M::worker_pipeline::236.688*21.30] mapped 258720 sequences
[M::mm_idx_gen::257.210*19.72] collected minimizers
[M::mm_idx_gen::257.245*19.73] sorted minimizers
[M::main::257.245*19.73] loaded/built the index for 30 target sequence(s)
[M::mm_mapopt_update::257.245*19.73] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 30
[M::mm_idx_stat::257.283*19.72] distinct minimizers: 2201523 (87.94% are singletons); average occurrences: 1.360; average spacing: 1360.239; total length: 4071164743
[M::worker_pipeline::270.896*21.55] mapped 834111 sequences
[M::worker_pipeline::274.522*21.28] mapped 258720 sequences
[M::mm_idx_gen::293.562*20.00] collected minimizers
[M::mm_idx_gen::293.596*20.00] sorted minimizers
[M::main::293.596*20.00] loaded/built the index for 31 target sequence(s)
[M::mm_mapopt_update::293.596*20.00] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 31
[M::mm_idx_stat::293.635*20.00] distinct minimizers: 2127784 (92.47% are singletons); average occurrences: 1.243; average spacing: 1519.365; total length: 4019781606
[M::worker_pipeline::306.094*21.46] mapped 834111 sequences
[M::worker_pipeline::307.578*21.36] mapped 258720 sequences
[M::mm_idx_gen::326.612*20.20] collected minimizers
[M::mm_idx_gen::326.645*20.20] sorted minimizers
[M::main::326.645*20.20] loaded/built the index for 28 target sequence(s)
[M::mm_mapopt_update::326.645*20.20] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 28
[M::mm_idx_stat::326.666*20.20] distinct minimizers: 1353674 (86.80% are singletons); average occurrences: 1.500; average spacing: 1985.247; total length: 4032155065
[M::worker_pipeline::337.873*21.30] mapped 834111 sequences
[M::worker_pipeline::338.461*21.26] mapped 258720 sequences
[M::mm_idx_gen::360.303*20.07] collected minimizers
[M::mm_idx_gen::360.336*20.07] sorted minimizers
[M::main::360.336*20.07] loaded/built the index for 34 target sequence(s)
[M::mm_mapopt_update::360.336*20.07] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 34
[M::mm_idx_stat::360.357*20.07] distinct minimizers: 1490499 (90.78% are singletons); average occurrences: 1.483; average spacing: 1884.499; total length: 4166517919
[M::worker_pipeline::370.689*20.97] mapped 834111 sequences
[M::worker_pipeline::371.280*20.94] mapped 258720 sequences
[M::mm_idx_gen::391.071*19.96] collected minimizers
[M::mm_idx_gen::391.103*19.96] sorted minimizers
[M::main::391.103*19.96] loaded/built the index for 28 target sequence(s)
[M::mm_mapopt_update::391.103*19.96] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 28
[M::mm_idx_stat::391.122*19.96] distinct minimizers: 1371016 (90.53% are singletons); average occurrences: 1.245; average spacing: 2354.402; total length: 4017895798
[M::worker_pipeline::401.565*20.67] mapped 834111 sequences
[M::worker_pipeline::406.741*20.42] mapped 258720 sequences
[M::mm_idx_gen::427.409*19.51] collected minimizers
[M::mm_idx_gen::427.448*19.51] sorted minimizers
[M::main::427.448*19.51] loaded/built the index for 36 target sequence(s)
[M::mm_mapopt_update::427.448*19.51] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 36
[M::mm_idx_stat::427.467*19.51] distinct minimizers: 1137515 (88.41% are singletons); average occurrences: 1.828; average spacing: 2000.733; total length: 4160490061
[M::worker_pipeline::437.251*20.28] mapped 834111 sequences
[M::worker_pipeline::437.739*20.26] mapped 258720 sequences
[M::mm_idx_gen::456.524*19.49] collected minimizers
[M::mm_idx_gen::456.554*19.49] sorted minimizers
[M::main::456.554*19.49] loaded/built the index for 29 target sequence(s)
[M::mm_mapopt_update::456.554*19.49] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 29
[M::mm_idx_stat::456.575*19.49] distinct minimizers: 971232 (74.54% are singletons); average occurrences: 1.641; average spacing: 2518.335; total length: 4014818016
[M::worker_pipeline::464.871*20.03] mapped 834111 sequences
[M::worker_pipeline::465.682*20.00] mapped 258720 sequences
[M::mm_idx_gen::485.658*19.24] collected minimizers
[M::mm_idx_gen::485.690*19.24] sorted minimizers
[M::main::485.690*19.24] loaded/built the index for 29 target sequence(s)
[M::mm_mapopt_update::485.690*19.24] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 29
[M::mm_idx_stat::485.709*19.24] distinct minimizers: 1085952 (89.39% are singletons); average occurrences: 1.334; average spacing: 2764.143; total length: 4004787517
[M::worker_pipeline::494.932*19.78] mapped 834111 sequences
[M::worker_pipeline::495.380*19.77] mapped 258720 sequences
[M::mm_idx_gen::515.892*19.04] collected minimizers
[M::mm_idx_gen::515.918*19.04] sorted minimizers
[M::main::515.918*19.04] loaded/built the index for 25 target sequence(s)
[M::mm_mapopt_update::515.918*19.04] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 25
[M::mm_idx_stat::515.936*19.04] distinct minimizers: 903622 (91.47% are singletons); average occurrences: 1.210; average spacing: 3717.716; total length: 4065292668
[M::worker_pipeline::523.078*19.45] mapped 834111 sequences
[M::worker_pipeline::524.651*19.39] mapped 258720 sequences
[M::mm_idx_gen::545.097*18.72] collected minimizers
[M::mm_idx_gen::545.122*18.73] sorted minimizers
[M::main::545.122*18.73] loaded/built the index for 31 target sequence(s)
[M::mm_mapopt_update::545.122*18.73] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 31
[M::mm_idx_stat::545.139*18.73] distinct minimizers: 876617 (88.45% are singletons); average occurrences: 1.273; average spacing: 3650.923; total length: 4075269801
[M::worker_pipeline::552.278*19.10] mapped 834111 sequences
[M::worker_pipeline::552.646*19.09] mapped 258720 sequences
[M::mm_idx_gen::572.714*18.48] collected minimizers
[M::mm_idx_gen::572.738*18.48] sorted minimizers
[M::main::572.738*18.48] loaded/built the index for 33 target sequence(s)
[M::mm_mapopt_update::572.738*18.48] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 33
[M::mm_idx_stat::572.749*18.48] distinct minimizers: 663392 (92.63% are singletons); average occurrences: 1.221; average spacing: 5005.300; total length: 4053747445
[M::worker_pipeline::578.368*18.73] mapped 834111 sequences
[M::worker_pipeline::578.695*18.72] mapped 258720 sequences
[M::mm_idx_gen::589.693*18.40] collected minimizers
[M::mm_idx_gen::589.726*18.40] sorted minimizers
[M::main::589.726*18.40] loaded/built the index for 185 target sequence(s)
[M::mm_mapopt_update::589.726*18.40] mid_occ = 770
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 185
[M::mm_idx_stat::589.766*18.40] distinct minimizers: 1792209 (66.14% are singletons); average occurrences: 2.181; average spacing: 555.888; total length: 2172634063
[M::worker_pipeline::614.863*19.61] mapped 834111 sequences
[M::worker_pipeline::624.639*19.32] mapped 258720 sequences
[M::main] Version: 2.17-r974-dirty
[M::main] CMD: minimap2 --cs -ax splice -t 70 /Drive1/human_index/Homo_sapiens.GRCh38.dna.toplevel.fa ./transcript/control_processed.fasta
[M::main] Real time: 624.886 sec; CPU: 12069.882 sec; Peak RSS: 34.236 GB
2021-05-30 13:32:19: Processing transcriptome alignment file: sam
2021-05-30 13:32:22: Processing genome alignment file: sam
Traceback (most recent call last):
  File "/home/aclab/apps/NanoSim/src/read_analysis.py", line 713, in <module>
    main()
  File "/home/aclab/apps/NanoSim/src/read_analysis.py", line 660, in main
    align_transcriptome(in_fasta, prefix, aligner, num_threads, t_alnm, ref_t, g_alnm, ref_g)
  File "/home/aclab/apps/NanoSim/src/read_analysis.py", line 131, in align_transcriptome
    get_primary_sam.primary_and_unaligned(g_alnm, prefix + "_genome")
  File "/home/aclab/apps/NanoSim/src/get_primary_sam.py", line 89, in primary_and_unaligned
    in_sam_file = pysam.AlignmentFile(sam_alnm_file, 'r')
  File "pysam/libcalignmentfile.pyx", line 737, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 986, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False

Thanks in Advance

**Comment by aman21392** [comment]
Thanks Chen, now it sort out. It is the genome file through which I got the error. I changed it and it working fine now.
