### ISSUE TITLE
Regarding simulate output

### ISSUE THREAD

**Issue by aman21392** [bcgsc/NanoSim#122]
So I ran nanosim through transcript mode. So I get 2 fasta file, one is control_simulate_aligned_reads.fasta
control_simulate_unaligned_reads.fasta

So I just want to know that the unaligned_reads.fasta are also simulated or they are as it is without simulated reads.
Please just clarify it. Thanks in advance

**Comment by cheny19** [comment]
They are simulated reads with high error rates, so theoretically they cannot be aligned to the reference.

**Comment by aman21392** [comment]
So it means we can not use those reads further for any analysis.
Thanks

**Comment by SaberHQ** [comment]
Whether to use or not to use "unaligned" read set depends on your analysis and research problem. In general, one would only use the "aligned" read set in any downstream analysis.

I also suggest you to take a look at Trans-NanoSim paper in which you can get more info about unaligned read sets. Let us know if you have any question. Thanks.

https://academic.oup.com/gigascience/article/9/6/giaa061/5855462

**Comment by aman21392** [comment]
ok thanks, I look at this paper.
