### ISSUE TITLE
Simulator execution error: "ImportError: No module named request"

### ISSUE THREAD

**Issue by ChristosMatzoros** [bcgsc/NanoSim#125]
Hello,

When I try to run simulator.py, even with no parameters I get this:

> ./simulator.py 
Traceback (most recent call last):
  File "./simulator.py", line 23, in <module>
    from urllib.request import Request, urlopen
ImportError: No module named request

I have installed all the required packages so I do not know what exactly is the problem in my case. Do I need to change the code?

**Comment by SaberHQ** [comment]
Hey @ChristosMatzoros were you able to successfully run NanoSim with Python3? I hope @cheny19 's suggestion worked for you. I am closing this issue as for now. Please feel free to reopen it if you still got issue with NanoSim. Cheers.
