### ISSUE TITLE
Are the parameters of the pre-trained models available?

### ISSUE THREAD

**Issue by dpellow** [bcgsc/NanoSim#134]
Are parameters of the pre-trained models such as error rates, length distribution etc reported somewhere?

**Comment by SaberHQ** [comment]
Hey @dpellow Thanks for your question and sorry for late response as I was away from work for a while. 

You may find all those information within each pre-trained model directory. For example you may get information about the error rates inside the *error_rate.tsv file. Length distribution information is stored as .pkl files as well. 

I hope this answers your question. If you have more specific question or any other issues, please let me know and I will do my best to help you with that.

**Comment by SaberHQ** [comment]
Hey @dpellow 

Hope you were able to find the answer you were looking for. I am closing this issue for now. Please feel free to reopen and ask any other questions if you need help.
