### ISSUE TITLE
Issue of fixed transcriptome read length generated by Nanosim for single thread

### ISSUE THREAD

**Issue by Tidesun** [bcgsc/NanoSim#155]
Hi,

I have found an issue that all the simulated reads for the same transcript will have the same read length if setting the number of threads to 1. It seems that each thread will yield the same read length for the same transcript.
I believe this is due to the simulation of read length from the KDE model is not conducted per read. 

Thanks,
Haoran

**Comment by SaberHQ** [comment]
Thanks for reporting this Haoran. We did some tests on this and I can confirm that there is an issue as you mentioned. I am working on it, doing some analysis, and I will push an update to fix it shortly. I will keep you updated.

**Comment by SaberHQ** [comment]
Dear @Tidesun ,

Please note that I did bunch of analysis and tested different approaches to fix your reported issue. I can confirm that the one you suggested works well and therefore, I incorporated your suggested fix into a pull request and updated the NanoSim repository. 

I am closing the issue. Please let me know if you have any more question. Cheers.
