### ISSUE TITLE
Update dependent package requirements

### ISSUE THREAD

**Issue by kmnip** [bcgsc/NanoSim#159]
A few packages should be updated to newer versions:
- numpy (as per https://github.com/bcgsc/NanoSim/security/dependabot/1)
- scikit-learn (version 1.0.x)

So, both NanoSim's [requirments.txt](https://github.com/bcgsc/NanoSim/blob/master/requirements.txt) and the [bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/nanosim/meta.yaml) need to be updated.

**Comment by SaberHQ** [comment]
Thanks for reporting this. Pull request #158 will update the required packages to their newer versions.
