### ISSUE TITLE
Maybe a bug in the error_list function

### ISSUE THREAD

**Issue by karel-brinda** [bcgsc/NanoSim#16]
Hi, I am just wondering if the `error_list` function works correctly. When creating an `e_dict`, it sometimes introduces steps of a negative length. I think that it might cause problems in the `mutate_read` function as it assumes (without any checking) that the step length (`val[1]`) will be positive. The program does not crash but I am afraid that the resulting data do not fully correspond to the used model. To observe the problem, you can use `assert key>=0` after `key = int(round(key))`.

**Comment by cheny19** [comment]
Hi Karel,

I double checked the `error_list` function and did not notice any negative or 0 step sizes. I also checked the distribution of each error type produced by this function, and statistic tests show they are the same as the original distribution.
