### ISSUE TITLE
reads headers empty in fasta file

### ISSUE THREAD

**Issue by jlipovac** [bcgsc/NanoSim#168]
Hi,

I'm trying to simulate metagenome reads (including chimeric reads) using pre-trained model and I succeeded in it but I got fasta file of simulated aligned reads with reads that have no headers. Something like this:
```
>
CAAAATCATAATACGGACGTTCAATTCAACAGCACCAACAAGAAAAACCAGCAGGCCGGCACCTTCGGCTGTTGGCTAAGTACCCCAAGCAAGCCTGATCGTCGTTGGGATGACCCTCGGGGGACGATGGTGTTCTACACTTTTACCACCTACTTGCAACAGTTCATGATCAACACGACCGGCCTGTCTAAGGAAAGTGCGCGCAGATGTTTTCTTCGTCGAGCTGCTGGTTGGAGTCCAACCGGTTCGGTCACGCATCCGATAGATTGCCGCAGCGCTCTTGATCTCTTCGGGGTCGGCGGAACCATCTTGACCGTGCCGCTGCCTT...
>
TTTTACGCGAGTCCTTCTATTTTAATTACATAAAAAAAAGCAGTACTTAATTAGCACTACCCTATGTCAAATGTTCATTAAAATTACAATAGAATTCTATTTAAATTTACCCACCTTTTAGATCTGTTACCACTAGCTTTCATATCAATCAAAAGTTGCTG...
```

In the file with simulated unaligned reads **there are** normal headers. 

I'm wondering did I maybe make a mistake in genome list, abundance or dna type tsv files?

Genome list looks like:
```
genome1_name   path1
genome2_name   path2
genome3_name   path3
genome4_name   path4
```

Abundance:
```
Size   10000
genome1_name   40
genome2_name   20
genome3_name   10
genome4_name   30
```

Dna type:
```
genome1_name   genome1_complete_genome   circular
genome2_name   genome2_complete_genome   circular
genome3_name   genome3_complete_genome   circular
genome4_name   genome4_complete_genome   circular
```

Thanks.

**Comment by kmnip** [comment]
Hi @jlipovac ,

It looks like this is related to pull-request #167, which is pending review now. 

Ka Ming

**Comment by kmnip** [comment]
Hi @jlipovac ,

I have merged the PR. The changes should be in the master branch now. Let us know if you still have any issues.

Ka Ming

**Comment by jlipovac** [comment]
Hi @kmnip, now it works! Thank you very much! :)

**Comment by jackchen129** [comment]
@kmnip I also have this issue using 3.1.0. Is it fixed in another release? Thanks.

**Comment by lcoombe** [comment]
Closing old issues - please feel free to open a new issue if you have further questions!
