### ISSUE TITLE
Could not retrieve index file for alignments

### ISSUE THREAD

**Issue by kosmasgal** [bcgsc/NanoSim#174]
Hi, like in Issue #130, I notice that after every successful transcriptome run of `read_analysis.py`, I get this message for each alignment produced during the model creation:

`[E::idx_find_and_load] Could not retrieve index file for`

In the replies to the issue, you mention that this error doesn't affect anything and we can safely ignore it, but it is also mentioned that it shouldn't come up for later versions of NanoSim. I am currently using NanoSim 3.1.0 in a docker container containing all the prerequisites and I still see it every run.
The model seems to work perfectly fine in producing simulated reads as far as I can tell. I just thought I would double check that I am doing everything right. Thanks

**Comment by kmnip** [comment]
Two error messages were reported in #130.

You can safely ignore this particular message about the index file.

The other error message (that you did not see in your log) should have been fixed in more recent releases.

Hope that helps!

**Comment by kosmasgal** [comment]
Great, thanks :)
