### ISSUE TITLE
Abnormal error distribution in reads

### ISSUE THREAD

**Issue by zhiliangfu** [bcgsc/NanoSim#175]
Hi, i am using nanosim to simulate amplicon reads with the code:
```
    ref=~/bsi/pipeline/data/ref_mapped/bf.mapped.fasta  # 716bp
    model=~/softwares/NanoSim/pre-trained_models/human_NA12878_DNA_FAB49712_guppy/training

    simulator.py genome \
      --ref_g $ref --model_prefix $model \
      --output ~/bsi/test/nanosim/bf/simulated \
      --number 80  --max_len 715  --min_len 705 --median_len 710 --sd_len 0.00001 \
      -dna_type linear --strandness 1.0 \
      --seed 10 -b guppy --fastq \
      --num_threads 4
```
but when i mapped the aligned_reads to ref, the same position of ref in different reads tends to have the same error type like below
![image](https://user-images.githubusercontent.com/43460308/205481319-91ac574a-2c8b-49ed-95b5-da6bb446bfdb.png)

is this normal?

**Comment by kmnip** [comment]
Hi @zhiliangfu ,
Can you please report the exact version you used?
Thanks!

**Comment by zhiliangfu** [comment]
> Hi @zhiliangfu , Can you please report the exact version you used? Thanks!

it seems that i made a mistake... there is a local reference, but in order to simulate the truth cases, i used a new refenrence to simulate fq, and mapped the simulated reads to local reference. There is a slightly difference between the two references.  so when the nucleotide of the simulated reads in the same position is the same as new reference, they may be different from the local reference because of the differences between the two references (as shown in above pic). i have checked that. i am so sorry for my mistake.

**Comment by kmnip** [comment]
No problem, that makes sense. I am glad you found out what the issue was!
