### ISSUE TITLE
Simulating exact number of reads for each input -- transcriptome mode

### ISSUE THREAD

**Issue by kosmasgal** [bcgsc/NanoSim#176]
Hi!
I am using my own model to simulate transcriptome reads from a FASTA input containing about 1000 gene isoforms.
I generate my own expression tsv file, by assigning each isoform an equal TPM, in such a way that it all adds up to 1 million.
I then simulate trans reads and I would like to have 1000 reads over each isoform in my input. 
Thus, aside from all the input sequences having the same weight (TPM), I also calculate the number of reads to be simulated by multiplying the number of reads with a 1000.
I have also set “L36_reads_alignment_rate” to 100% for the model, so that only aligned reads are simulated.

The number of reads however seems to follow some kind of distribution, with the lowest depth locus having only 2 reads over it. The bias seems to be towards longer isoforms having more reads over them. I am not sure I understand completely how the code works yet, but this may be the culprit: 
```            else:
                ref_len_aligned = select_nearest_kde2d(sampled_2d_lengths, ref_trx_len)
                if ref_len_aligned < ref_trx_len:
                    break 
```
Is it possible for me get the exact number of reads I want for each input in my FASTA without just simulating a crazy number of reads?

**Comment by SaberHQ** [comment]
Hi @kosmasgal and sorry for this late reply. 

I totally got your question. However, I have to say that as you correctly pointed out, NanoSim works based on statistical modelling approaches which means it draws read lengths from the 2-dimensional KDE distribution for example. 

In the code block, as you correctly mentioned, the `select_nearest_kde2d` function samples a length from the 2D KDE distribution based on the length of the selected reference transcript.  

Please note that NanoSim is super fast in simulating reads. For your scenario, I would suggest simulating millions of reads and then sub-sample an equal number of reads for each transcript. 

Let us know if you have any other questions.

**Comment by kosmasgal** [comment]
Thank you very much for your reply and explanation!
