### ISSUE TITLE
Models for R10.3 or R10.4 flow cell

### ISSUE THREAD

**Issue by zhenLiuXplr** [bcgsc/NanoSim#187]
Hi

Nanopore comunnity has already published the R10.3 and R10.4 flow cell, with much higher accuracy. I'm wondering is there any models that can be used in R10 flow cell cDNA/directRNA simulation.

**Comment by lcoombe** [comment]
Hi @zhenLiuXplr,
While we don't currently have pre-trained models for those new chemistries in transcriptome mode, we would welcome any suggestions of potential datasets to use for this training!
