### ISSUE TITLE
Please specify the training reads and its reference genome!

### ISSUE THREAD

**Issue by kainth-amoldeep** [bcgsc/NanoSim#191]
Hi, I installed nanosim using `conda install -c bioconda nanosim` and then tried to run the read characterization using 
`read_analysis.py transcriptome -i training_reads.fastq -rg reference_genome.fa -rt reference_transcriptome.fa -annot reference_annotation.gtf -o training`. However, I get the following error:
**Please specify the training reads and its reference genome!
./read_analysis.py <options>
<options>: 
-h : print usage message
-i : training ONT real reads, must be fasta files
-r : reference genome of the training reads
-a : Aligner to be used: minimap2 or LAST, default = 'minimap2
-m : User can provide their own alignment file, with maf or sam extension, can be omitted
-b : number of bins (for development), default = 20
-t : number of threads for LAST alignment, default = 1
-o : The prefix of output file, default = 'training'
--no_model_fit : Skip the model fitting step**
I am sure that the path to the respective files (training_reads and reference_genome) is correct. I have also tried feeding fasta files instead of fastq but still get the same error. Please help. Thanks

**Comment by kmnip** [comment]
The command looks okay to me.

Can you report the version you are using?
```
python read_analysis.py -v
```

**Comment by kainth-amoldeep** [comment]
Hi, you are right; my conda installation somehow installed an old version of NanoSim. I proceeded to directly download the latest version (3.0) and ran the command again. It seems to be working now. Thanks a lot for reaching out.

**Comment by kmnip** [comment]
@kainth-amoldeep That's great to hear!
I am closing this issue now. Please create another issue if you encounter any more issues.
