### ISSUE TITLE
NanoSim for tuning Minimap2 parameters?

### ISSUE THREAD

**Issue by ammaraziz** [bcgsc/NanoSim#195]
Hi there,

Thank you for creating and maintaining NanoSim, great tool.

Could nanosim be used to fine tune the parameters of Minimap2? If so do you have any recommendation on how to extract the relevant data to help inform parameter selection.

A non complete list of minimap2 params I'd like to fine tune:

-  Gap open penalty
-  Minimizer window size
-  Mismatching penalty

Thanks!

**Comment by kmnip** [comment]
That's an interesting proposition; I think it can be done.

First, you will need to simulate a set of reads (with `simulator.py`). Note that each simulated read has the corresponding source region coordinates encode in its read name in the FASTQ file.
You can then align these simulated reads with minimap2 with a sweep of relevant parameters. You will need to check the accuracy of each alignment against the read name information mentioned previously.

**Comment by ammaraziz** [comment]
Thanks for the advice.

Is it possible to use the profiles generated using the different modes to help guide the parameter selection?
