### ISSUE TITLE
Using "sam" alignments with "read_analysis.py"

### ISSUE THREAD

**Issue by npavlovikj** [bcgsc/NanoSim#20]
Hi,

I would like to use my own alignment file with "read_analysis.py" and skip the default alignment with LAST. However, the alignment file I have is in "sam" format, and "read_analysis.py" requires alignment file in "maf" format. I was wondering if it is possible to use "sam" alignments in this step, or if not, do you know how can I convert the "sam" files to "maf" ones ?

Thank you,
Natasha

**Comment by cheny19** [comment]
Hi Natasha,

Here's how I convert `sam` to `MAF`:

First, I use a tool called `sam2pairwise` and convert `sam` to `pairwise` format. The github page is here: https://github.com/mlafave/sam2pairwise

Next, I wrote an script to convert `pairwise` to `MAF`. I just uploaded it to this repo. It should do the work, but I haven't fully tested the script yet, so it might break at some edge cases. 

Let me know if you have any problems running it.

Thanks,
Chen
