### ISSUE TITLE
Support for Dorado?

### ISSUE THREAD

**Issue by weishwu** [bcgsc/NanoSim#201]
Any plan to add `dorado` to `--basecaller`? Thanks.

**Comment by SaberHQ** [comment]
Dear @weishwu Thank you for bringing this up. We do have plans to include `dorado` to `--basecaller` in the next release. However, I can not give you an exact date for it. It should be within the next month or so. I will make sure to keep you updated.

**Comment by weishwu** [comment]
Thanks!
