### ISSUE TITLE
How to find reference genome for pre-trained models

### ISSUE THREAD

**Issue by Evandio-Martin** [bcgsc/NanoSim#204]
Hi, I am new to the NanoSim. I'm interested in trying the ./simulation.py from the pre-trained model of human_NA12878_DNA_FAB49712_guppy_flipflop

I tried using this command
./simulator.py genome -dna_type linear -rg /Users/evan/Downloads/GRCh38_latest_rna.fna -c /Users/evan/NanoSim/pre-trained_models/human_NA12878_DNA_FAB49712_guppy_flipflop/training -max 10000 -min 1000

The reference genome is from this website
https://www.ncbi.nlm.nih.gov/genome/guide/human/

where I used the GRCh38's Refseq Transcripts fasta

Is it right to use that reference genome from that website, to put directly into nanosim? Or is there another website that is more suitable for reference genomes of the pre-trained models?

Thank you very much!

**Comment by kmnip** [comment]
If you are trying to simulate genomic reads, please use the reference genome FASTA --- not the reference transcripts FASTA!

**Comment by Evandio-Martin** [comment]
Thank you very much for the answer. I will change it into the reference genome FASTA
