### ISSUE TITLE
Coverage breadth following metagenome characterization

### ISSUE THREAD

**Issue by ezherman** [bcgsc/NanoSim#205]
Hi, thanks for building this awesome tool! I have been playing with the metagenome abundance profile feature of NanoSim. I am interested in estimating coverage breadth (and depth) following quantification with `read_analysis.py metagenome` and the options `-gl -c -q --no_model_fit`.

Is it possible to infer the reference position to which each base was assigned from the NanoSim output?

**Comment by kmnip** [comment]
If I am not mistaken, metagenome abundance is quantified based on fractional assignment of reads using an EM algorithm. So, no additional information is inferred on individual base of each read used during quantification.

**Comment by ezherman** [comment]
Hi @kmnip, thanks for getting back to me. Yes, makes sense now that I've looked at the EM algorithm more closely. I can imagine an extension may update the read assignment given `perc_for_species` for reads in `multi_mapped_reads`, but I'm not in a position now to play around with that!
