### ISSUE TITLE
output different replicates of a sample

### ISSUE THREAD

**Issue by zzare-umd** [bcgsc/NanoSim#214]
Hi, 

Thank you for providing such a great software tool. I am currently using NanoSim to simulate an ONT cDNA dataset from a FASTQ file. I would like to generate different replicate samples. Can this be achieved by changing the "seed" value during the simulation?

Regards,
Zahra

**Comment by lcoombe** [comment]
Hi Zahra,

Running NanoSim multiple times with the same settings (except for using a different output prefix, of course) will yield different simulated read sets. NanoSim samples from various distributions, and is not deterministic. You can verify this by running `abyss-fac` or a similar utility on the simulated reads, and will see that their N50, sum, max length, etc. should be non-identical.

Thank you for your interest in NanoSim!
Lauren
