### ISSUE TITLE
Minimap2 version (2.11) co-installed with conda without `--cs` parameter

### ISSUE THREAD

**Issue by capoony** [bcgsc/NanoSim#219]
Dear all, 

thanks for the great software! I, however, identified a small bug. The minimap2 version 2.11, which is installed by conda together with nanosim does not know the `---cs` parameter, which leads to downstream errors in `read_analysis.py`.

My quick fix was to update minimap to the latest version (2.28) in the conda environment:

```bash
conda create -y --name nanosim -c conda-forge nanosim
conda activate nanosim
conda install minimap2=2.28
```

Best, Martin

**Comment by capoony** [comment]
...this concerns NanoSim v.3.2

**Comment by lcoombe** [comment]
Hi Martin,

Thanks for pointing this out. While generally conda will install the most up-to-date versions of dependencies (like minimap2) in your environment, sometimes it will install other versions depending on what other tools you have installed already in your environment.

I have opened a PR to update the conda recipe to specify the minimum minimap2 version that should be installed (https://github.com/bioconda/bioconda-recipes/pull/50576)

Thank you for your interest in NanoSim!
Lauren

**Comment by capoony** [comment]
Thanks a lot :-)
