### ISSUE TITLE
GPL3 and commercial license

### ISSUE THREAD

**Issue by james-vincent** [bcgsc/NanoSim#229]
Is a commercial license _required_ for use by a commercial entity? The license text is unclear. The GPLv3 explicitly allows commercial use of software.

**Comment by warrenlr** [comment]
Thank you for your inquiry @james-vincent.

We will get back to you on this matter, thanks for your patience.
Rene

**Comment by warrenlr** [comment]
Companies are not restricted from using software under GPLv3, as you indicated.  
The GPLv3 license has certain restrictions, however, and the intent of that notice in our license is to provide commercial entities with alternate options. We invite you to reach out to our technology development office for further clarifications (Patrick Rebstein <prebstein@bccancer.bc.ca>)
