### ISSUE TITLE
using nanosim to generate fastq files?

### ISSUE THREAD

**Issue by nick-youngblut** [bcgsc/NanoSim#26]
Is there a way to make fastq files with `nanosim`? It seems to me that it would be preferable to generate fastq versus fasta files, so that nanopore QC software (eg., [nanofilt](https://github.com/wdecoster/nanofilt)) can be run on the fastq files.

**Comment by cheny19** [comment]
Hi @nick-youngblut,

After two years, we finally have the fastq format option in release V2.6.0. Hope it's not too late for you!

Chen
