### ISSUE TITLE
Read Output ID

### ISSUE THREAD

**Issue by JustinChu** [bcgsc/NanoSim#3]
Relative to the comments in the readme:

> \>ref|NC-001137|-[chromosome=V]_468529_unaligned_0_F_0_3236_0
All information before the first _ are chromosome information. 468529 is the start position and unaligned suggesting it should be unaligned to the reference. The first 0 is the sequence index. F represents a forward strand. 0_3236_0 means that sequence length extracted from the reference is 3236 bases.
> \>ref|NC-001143|-[chromosome=XI]_115406_aligned_16565_R_92_12710_2
This is an aligned read coming from chromosome XI at position 115406. 16565 is the index of simulation. R represents a reverse complement strand. 92_12710_2 means that this read has 92-base head region (cannot be aligned), followed by 12710 bases of middle region, and then 2-base tail region.

The 4th field confuses me. Is it "index of simulation" or "seqeunce index" and what does this mean? Is it basically a unique read ID? If so, why does the numbering reset when transitioning between unaligned reads and aligned reads?

eg. an example of what I see in the output:
\>ref|NC-001137|-[chromosome=V]_468529_unaligned_123_F_0_3236_0
\>ref|NC-001143|-[chromosome=XI]_115406_aligned_0_R_92_12710_2
The numbering resets, if intended to be a ID of sorts (which will be useful, as I may want to convert the header to something simpler) they should not reset.

**Comment by cheny19** [comment]
Sequence index is a unique read ID and it's fixed now.
