### ISSUE TITLE
Read Simulation: reference length limitation?

### ISSUE THREAD

**Issue by ampodu** [bcgsc/NanoSim#30]
Hi,
I was hoping to use this tool to simulate some reads for a set of amplicons. However, it gives me an error when I try it:
```
src/simulator.py linear -r ~/R/projects/umi.sim/nanosim.input.fasta -c training.juplasmid -o
sim.pcrprod
Traceback (most recent call last):
  File "src/simulator.py", line 716, in <module>
    main()
  File "src/simulator.py", line 710, in main
    simulation(ref, out, dna_type, perfect, kmer_bias, max_readlength, min_readlength)
  File "src/simulator.py", line 284, in simulation
    read_mutated = mutate_read(new_read, new_read_name, out_error, error_dict, kmer_bias, False)
  File "src/simulator.py", line 577, in mutate_read
    tmp_bases.remove(read[key + i])
IndexError: string index out of range
```
the reference file contains 10 000 entries with a size of 1,3 kb. So I thought maybe it can not deal with so many entries. That is why I tried the simulation with a plasmid of 7.4 kb, but that outputs the same error.

When I try it with a 49kb lambda genome it works, that is why I assume there is a limitation in the reference size?

Is it possible to adjust NanoSim for shorter references or am I missing something?

**Comment by cheny19** [comment]
NanoSim is able to deal with multiple entries in a fasta file and it should work fine for small reference genomes, just take longer to generate a proper read length. Could you send me your reference plasmid fasta file so I can test on it? Thanks!

**Comment by ampodu** [comment]
I send the file to your bcgsc.ca mail address.

I did some more testing and it seems that every reference over ~40kb works but with ~20kb or less it always crashes for me. However, if I use --perfect, it works just fine. The problem probably lies within mutate_read.

**Comment by ampodu** [comment]
I found a solution: specifying the "max_len" as the length of the reference contigs.
Seems like it was trying to create reads longer than the reference?

**Comment by cheny19** [comment]
I got the email. I'll do some test and let you know later this week.
