### ISSUE TITLE
 power overflow

### ISSUE THREAD

**Issue by std-libchen** [bcgsc/NanoSim#32]
Hi,
When I was running the read_analysis file, I got this:

/mixed_model.py:25: RuntimeWarning: overflow encountered in power
  wei_cdf = 1 - np.exp(-1 * np.power(x / l, k))

I was wondering if any action is required for this warning.

**Comment by cheny19** [comment]
Sorry, somehow I missed this issue... No, you don't need to take any actions, just continue to the following simulation stage.
