### ISSUE TITLE
Excuse me. You program can take consider the coverage information?

### ISSUE THREAD

**Issue by xiangni128182** [bcgsc/NanoSim#33]
Excuse me. If I consider the coverage of simulated reads, what should I do?

For example, I have 10 contigs in the reference fasta file. If I want to generate simulated reads with a 10X coverage, how can I set the parameters to get reads?

Thank you!

**Comment by cheny19** [comment]
Hi,

First, you need to calculate the size of the genome you are trying to simulate, which is the sum of 10 contigs in your case. Then 10X coverage means on average, each based is covered 10 times, so 10 * genome size is the total number of bases you want to simulate. Suppose the average length of your training reads is x, then you will probably need total number of bases / x reads. Hope that helps. Please keep in mind that if the contig length is shorter than the average training read length, you probably won't get the coverage you need.

Thanks,
Chen

**Comment by harisankarsadasivan** [comment]
when the length of reference is greater than the template used for training, we configure the max_len parameter right? In this case, should the x in the above formula be replaced with the max_len value?

**Comment by cheny19** [comment]
The x here is the average read length, not max_len. But if your max_len and min_len range is very different from the training set, it should be changed accordingly.
