### ISSUE TITLE
.log file for read_analysis.py? (Killed error)

### ISSUE THREAD

**Issue by FiniDG** [bcgsc/NanoSim#34]
I try to run read_analysis.py for some time now. Now I am at a stage where I get "Killed" everytime after a while, with no error code or other explanation. Other errors in the past I could solve with the python errors I got, but here I got nothing. The simulator.py does seem to give a log file (according to the readme), but the read_analysis.py doesn' t seem to have this, so I cannot look into what goes wrong.

#copy/paste of my terminal screen:
```
[user@01 ~]$ cd Documents/tools/NanoSim/src/
[user@01 src]$ python read_analysis.py -i /path/to/reads/ERR2173373.fasta -r /path/to/ref/OMOL01.fasta -m /path/to/sam/arabidopsis_minimap_CStag.sam -o /path/to/output 
2018-10-26 08:04:04: Read pre-process and unaligned reads analysis
2018-10-26 08:04:59: Processing alignment file: sam
2018-10-26 08:24:27: Aligned reads analysis
2018-10-26 08:41:20: match and error models
Killed
[user@01 src]$
```

p.s I made my own minimap2.sam, because the NanoSim variant keeps giving me a memory error. I did use the same parameters though.

**Comment by cheny19** [comment]
The log file of `read_analysis.py` is already printed on the screen. From what you just showed, we can tell that the program is killed during the error model fitting stage. It's likely that the program is using too much memory, but there're other possibilities. Could you provide me your input files, so I can try to re-produce the error and debug? Thanks!

**Comment by FiniDG-HAN** [comment]
The files are the files downloaded from the ebi website 
https://www.ebi.ac.uk/ena/data/view/PRJEB21270
https://www.ebi.ac.uk/ena/data/view/GCA_900303355

I wanted to train NanoSim on _Arabidopsis thaliana_ data, but I guess the files were just too big, because when I deleted half of the reads in the .sam file it worked, however it now gives me these errors about that the data might not be correct? Could you give me some guidelines how to train NanoSim with _Arabidopsis thaliana_ data?

```
2018-10-26 16:24:38: Mismatch fitting start
Mismatch parameters:  [0.34377365 0.78485674 0.05191   ] 7.148720692606858e-05
2018-10-26 16:25:52: Mismatch fitting done
2018-10-26 16:25:52: Insertion fitting start
WARNING! Insertion parameters may not be optimal!
 [0.90466316 1.02283723 0.06348935 0.99482725] 0.0007912303643020646
2018-10-26 17:16:41: Insertion fitting done
2018-10-26 17:16:41: Deletion fitting start
/home/user/NanoSim/src/mixed_model.py:25: RuntimeWarning: overflow encountered in power
  wei_cdf = 1 - np.exp(-1 * np.power(x / l, k))
/home/user/NanoSim/src/mixed_model.py:25: RuntimeWarning: overflow encountered in power
  wei_cdf = 1 - np.exp(-1 * np.power(x / l, k))
WARNING! Deletion parameters may not be optimal!
 [1.15559321 1.0519236  0.30252621 0.83469677] 0.0014279099454098665
2018-10-26 18:26:25: Deletion fitting done
2018-10-26 18:26:25: Finished!
```

**Comment by cheny19** [comment]
Don't worry, the message above is just a warning, not an error. Since it says "Finished", it means that you can use the fitted model for the following simulation.
