### ISSUE TITLE
Unavailability of long Read MinION template

### ISSUE THREAD

**Issue by harisankarsadasivan** [bcgsc/NanoSim#35]
Hi,

As I understand, we need a long raw read from MinION for the simulator to do a read error profile characterization. I am unable to find raw long reads online apart from ecoli and yeast. Do we need reads of each genus to simulate artificial reads of that genus? For ex, I need artificial reads of 10 types of bacteria, do I need template reads for all 10 of them to configure the simulator?

**Comment by cheny19** [comment]
Not really, you can use the profile learnt from E. coli to simulate the 10 bacteria genome you need. NanoSim learns the profile of the sequencing platform, not the features of training genome.

**Comment by harisankar991** [comment]
I see. Thank you for the input. I want to use Nanosim to simulate a metagenome of a bacterial community. Do you suggest I simulate reads for individual genus and then mix the reads of each genus to get an artificial metagenome or can I directly use a raw metagenome read to simulate an artificial metagenome read?

**Comment by cheny19** [comment]
If your artificial metagenome is a mixture of bacteria genomes, then it's better to simulate them one by one because bacteria genomes are circular. For NanoSim, if your genome is circular, it only accepts one entry in the fasta input file. Also you need to specify it's circular in the command.
