### ISSUE TITLE
Requirement of latest nanopore MinION reads

### ISSUE THREAD

**Issue by harisankar991** [bcgsc/NanoSim#37]
Could you specify the nanopore version used for the input ecoli reads mentioned here? Is there latest MinION simulated reads with you, if so could you please share?

**Comment by cheny19** [comment]
Sorry, I don't have the latest simulated reads to share. The lastest version of error profiles can be found at our ftp site in the `README.md`, and you can run `simulate.py` from there to eliminate the time consuming training process.
