### ISSUE TITLE
Perfect option gives error

### ISSUE THREAD

**Issue by emilhaegglund** [bcgsc/NanoSim#4]
The `--perfect` option give the following error for me:

```
Traceback (most recent call last):
  File "./simulator.py", line 646, in <module>
    main()
  File "./simulator.py", line 638, in main
    read_profile(number, model_prefix, perfect)
  File "./simulator.py", line 156, in read_profile
    for i in xrange(number_unaligned):
UnboundLocalError: local variable 'number_unaligned' referenced before assignment
```

**Comment by cheny19** [comment]
Sorry, there's was an indentation problem. It's fixed now. Please download the new zip file and try it again.

**Comment by cheny19** [comment]
Hi,

I just noticed that the `--perfect` option only produced forward sequence. 

Now it's fixed. Please use the latest version.
