### ISSUE TITLE
Covering the entire genome

### ISSUE THREAD

**Issue by harisankar991** [bcgsc/NanoSim#40]
Does Nanosim simulate reads from every part of the reference genome? Is there a way to configure coverage or a minimum number of reads to ensure that the entire genome is covered. My requirement is that WGS assembly should be possible from the artificial reads generated.

**Comment by FiniDG-HAN** [comment]
I do know that issue #33 asks a similar problem. You can set the minimal number of reads with the -n parameter. The reads are as far as I know evenly distributed over the genome that you provide with the simulator.py
