### ISSUE TITLE
Is it possible to train the error model using a human DNA read and then simulate bacetrial genomic reads?

### ISSUE THREAD

**Issue by harisankar991** [bcgsc/NanoSim#41]
The reason I want to do this is because for the latest MinION chemistry, I have only human DNA reads with me and I want to simulate bacterial reads for the latest chemistry

**Comment by FiniDG-HAN** [comment]
you can look for publicly available data. For example, I found minION arabidopsis reads on the EBI website. Also in the readme it mentiones some bacterial sets I believe? with the program also comes a test.sh or something that simulates e coli I believe (I cannot check until tomorrow), but these should help already. With the trained data, you could simulate reads for almost every sequence you provide. (again I am not the developer, this is based on my own experience with the program)

**Comment by cheny19** [comment]
Yes, you can train on human DNA read and simulate a bacterial genome. Also, make sure you use the `circular` option when dealing with bacterial genome.
