### ISSUE TITLE
indexerror: string index out of range

### ISSUE THREAD

**Issue by harisankarsadasivan** [bcgsc/NanoSim#42]
What can I do if my reference genome is smaller than the reference used for training the error model? I get the error "indexerror: string index out of range" in this case.

**Comment by harisankarsadasivan** [comment]
I am getting the error even when I choose a reference genome for simulation longer than the template used for training.

**Comment by cheny19** [comment]
If your reference genome is smaller than the max length of your training reads, then you should specify the max length of your simulated reads using the option `max_len`.

**Comment by harisankarsadasivan** [comment]
Similarly, is there a condition where we should program min_len?

**Comment by cheny19** [comment]
If you don't want to have too short reads, you can use `min_len`
