### ISSUE TITLE
Make easy installable package using pip or bioconda

### ISSUE THREAD

**Issue by wdecoster** [bcgsc/NanoSim#44]
To increase ease of installation and dependency management, please consider adding your tool to pip/PyPI and/or bioconda. If you need any help getting this done please let me know.

**Comment by wdecoster** [comment]
I agree it is not too difficult to run, that doesn't stop your from making it easier. What installation would do in this case is:

- install the dependencies

- put the scripts in $PATH

People are getting used to just do `conda install nanosim` and expect things to work.

**Comment by splaisan** [comment]
I second Wouter here, it would be nice to have a conda build for the latest version (now installing 2.2.0 which is not the best if I understand well). Could you please consider pushing your code to conda please :-)

**Comment by fairliereese** [comment]
Additionally, I had to dig into the issues to find out how this tool is supposed to be installed.... at least add these instructions to the README please.

**Comment by cheny19** [comment]
Hello all,

Sorry for the late reply. I have included the conda badge at the top of the README and it links to the conda installation page, which shows instructions about how to install the latest release.

Cheers,
Chen
