### ISSUE TITLE
model fitting

### ISSUE THREAD

**Issue by jannaf** [bcgsc/NanoSim#46]
Hi,

I am trying to run NanoSim on a Drosophila dataset, I ran it fine on E. coli and other organisms but now I am getting this repeatedly (~10,000 times) in the model_fitting.Rout file

...
+ }
> 
> mis.fit.tmp1 <- mis_fit_func(LL.mis)
[1] "Try different initial value of MLE"
[1] "Try different initial value of MLE"

Do you have any ideas how to get around this or what is wrong? Thanks!

**Comment by cheny19** [comment]
Hi,

Could you download the latest release and give it a shot? I changed the code for model fitting from R to Python and you should not see this error message again.

Thanks!

**Comment by jannaf** [comment]
Hi

I did and now get a new error? Thanks for your help!

[M::mm_idx_gen::0.892*0.80] collected minimizers
[M::mm_idx_gen::1.018*1.19] sorted minimizers
[M::main::1.018*1.19] loaded/built the index for 17 target sequence(s)
[M::mm_mapopt_update::1.072*1.18] mid_occ = 33
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 17
[M::mm_idx_stat::1.106*1.17] distinct minimizers: 2084917 (95.68% are singletons); average occurrences: 1.093; average spacing: 5.336
[M::worker_pipeline::112.192*3.91] mapped 67357 sequences
[M::worker_pipeline::218.900*3.93] mapped 67283 sequences
[M::worker_pipeline::287.237*3.89] mapped 48422 sequences
[M::main] Version: 2.10-r761
[M::main] CMD: minimap2 --cs -ax map-ont -t 4 GCF_000146045.2_R64_genomic.fna scer_processed.fasta
[M::main] Real time: 287.303 sec; CPU: 1117.142 sec
2019-02-11 09:21:06: Read pre-process and unaligned reads analysis
2019-02-11 09:21:13: Alignment with minimap2
Traceback (most recent call last):
  File "/jlf/janna/bama_new/NanoSim-master/NanoSim-master/src/read_analysis.py", line 190, in <module>
    main(sys.argv[1:])
  File "/jlf/janna/bama_new/NanoSim-master/NanoSim-master/src/read_analysis.py", line 146, in main
    unaligned_length = get_primary_sam.primary_and_unaligned(out_sam, prefix)
  File "/jlf/janna/bama_new/NanoSim-master/NanoSim-master/src/get_primary_sam.py", line 14, in primary_and_unaligned
    if alnm.aligned and (not alnm.not_primary_alignment and not alnm.supplementary):
AttributeError: 'HTSeq._HTSeq.SAM_Alignment' object has no attribute 'supplementary'

**Comment by jannaf** [comment]
Hi, I think I figured it out- looks like it was a mismatch/bug with earlier Python/HTSeq/samtools versions. I transitioned entirely to Python3.6.5 and everything seems to be running now.
