### ISSUE TITLE
ecdf files are incorrectly written in head_align_tail_dist.py if max_length <25000

### ISSUE THREAD

**Issue by psarkozy** [bcgsc/NanoSim#5]
The last bin in the header is 25000-4194, this, along with the fact that the entire column of 4000-5000 is 0, results in a crash in simulator.py at https://github.com/bcgsc/NanoSim/blob/5c02a2e3d71924adfc8055cd82b8f6b0ae8502a2/src/simulator.py#L95
with IndexError
[vanilla_training_align_ratio.txt](https://github.com/bcgsc/NanoSim/files/240867/vanilla_training_align_ratio.txt)

Thank you for your attention!

**Comment by JustinChu** [comment]
Yeah, it is strange that your longest read from your dataset is 4294 (fairly short for nanopore data), but we should still be able to simulate using it. I'll try to provide a temporary quick fix soon.

@cheny19 I know you were experimenting with a version where the length bins used in the `align_ratio` were dynamically changed according to the data. What is the status of this?

**Comment by psarkozy** [comment]
This was an old sequencing run of BRCA1 amplicons with the first ONT, so the relative shortness was not unexpected. I just wanted to have a nice visual IGV look at the simulated error profiles. Anyhow the error was fixable with some text editing, so ill have a look at the results tomorrow. Thank you for your work!

**Comment by JustinChu** [comment]
I'm glad it worked out, I've just pushed quick a fix that should prevent us from generating file ecdf files with 0 in the columns, essentially generating the files that you created by text editing them.

@cheny19 - When you have time please review my changes. Also, I'm a bit concerned by the fixed bucket sizes we use when reads are not in the length range we used in testing - we should talk about this.

**Comment by cheny19** [comment]
Thanks Justin for the prompt fix.

I'll read and test your changes when I come back, namely next Monday. Actually, I tried flexible bucket sizes and they don't work as good as this fixed size. So I abandoned that version. We can talk about it next week.
