### ISSUE TITLE
all reads aligned bug?

### ISSUE THREAD

**Issue by machand** [bcgsc/NanoSim#50]
Hi developers
With a particular simulation we repeatedly get an error when starting the sim, because the file _unaligned_length.pkl has not been generated during training. This has not been a problem when running nanosim on our other datasets. Is this happening because  there are no unaligned reads in this particular training set?  Is there a way to sort this out so we can still get a sim from this dataset?
thanks!

**Comment by cheny19** [comment]
Hi, 

Thanks for bringing up this bug. Yes, it is because there's no unaligned reads, but the program is looking for some to build a kde model. We will fix it asap.

Thanks,
Chen

**Comment by baraaorabi** [comment]
I'm having the same problem too. Waiting for your fix. Thanks.

**Comment by cheny19** [comment]
Hi @machand and @baraaorabi,

The above-mentioned bug is fixed, please download the latest release and git it a shot.

Thanks,
Chen
