### ISSUE TITLE
Define read length parameters

### ISSUE THREAD

**Issue by Raymi1** [bcgsc/NanoSim#55]
Hello,

Is it possible to use a generic genome to train for error rates and the distribution, and to run the simulation stage with manually defined mean read length ?

Thanks for your help

**Comment by SaberHQ** [comment]
Hello @Raymi1 

You may use any kind of read set as input for the purpose of training and learning the error rates and length distribution. Check the following options in the simulation stage for what you are looking for:

--median_len
--sd_len
