### ISSUE TITLE
What does "WARNING! Deletion parameters may not be optimal!" mean?

### ISSUE THREAD

**Issue by harisankarsadasivan** [bcgsc/NanoSim#62]

**Comment by cheny19** [comment]
When NanoSim tries to fit the mixed statistical model, it performs a goodness of fit test (mostly for development purpose). When the fitted parameters fail to pass the test, it will output this warning. But normally the discrepancy is still very small, so the error rate and error patterns are close enough to the raw reads.

**Comment by SaberHQ** [comment]
Dear @harisankarsadasivan 

I hope Chen was able to answer your question. I am closing this issue. Please try the new releases and let us know if there is anything wrong.
