### ISSUE TITLE
RAM overload

### ISSUE THREAD

**Issue by ScatF** [bcgsc/NanoSim#64]
Hi,

I want to use NanoSim on big set of ONT data and allow it 5 threads to run. But during running I saw a RAM overload that forced me to stop the process. First the `read_analysys.py transcriptome` used minimap2 (it was okay at this step) and once completed It was using **216 G** of RAM to run . Fortunately I'm running on a working cluster with enough to not crash. It is normal ? Can you add a threshold for the memory use ?

I use this line to run : 
```
 ./NanoSim-v2.4-beta/src/read_analysis.py transcriptome -i /mypath/workspace/all.fa -rt /mypath/Homo_sapiens.GRCh38.cdna.all.fa  -o /mypath/training -t 5 -rg /mypath/Homo_sapiens.GRCh38.dna.primary_assembly.fa -annot /mypath/Homo_sapiens.GRCh38.97.chr.gtf 
```

Edit : I tried with the --no_intron_retention option and didn't overload the RAM

**Comment by SaberHQ** [comment]
Hi @ScatF , Would you mind to tell me the size of your input reads for training? I benchmarked it with 1 Million reads and it worked well. I can definitely test it with larger datasets and let you know my thoughts.

**Comment by SaberHQ** [comment]
Hey @ScatF, I wonder whether you had a chance to try our latest releases or not? The memory usage reduced and the speed improved a lot and we fixed many bugs since then. Please try the latest releases and give me your thoughts.
