### ISSUE TITLE
Know mean read length from training outputs

### ISSUE THREAD

**Issue by sdjebali** [bcgsc/NanoSim#66]
Dear all,
First of all thanks for this nice suite of tools and the associated documentation.
I just wanted to know if it was possible to get the mean read length from any of the training outputs?
Thanks,
Sarah

**Comment by cheny19** [comment]
Hi Sarah,

Sorry about the late reply. In the outputs, there are a few .txt files and one of them is the lengths of all aligned reads and another is the lengths of unaligned reads. If you add each row up and divide by the total number of rows, you'll get the mean read length.

Thanks,
Chen
