### ISSUE TITLE
How can I specify the Minimap2 location as it does not work?

### ISSUE THREAD

**Issue by Kumereng** [bcgsc/NanoSim#71]

**Comment by cheny19** [comment]
Hi @Kumereng ,

First, you need to make sure you have installed minimap2 and it's in your $PATH. You can check that by typing `which minimap2` in your command line. Once you made sure that, NanoSim will be able to find it and run. 

Let me know if you have trouble in that.

Chen

**Comment by Kumereng** [comment]
Thank you!
