### ISSUE TITLE
Overflow Warning

### ISSUE THREAD

**Issue by stopalopa** [bcgsc/NanoSim#73]
Hi, 
I received the following warning when running NanoSim on human nanopore reads when running read_analysis.py with 8 threads: 

NanoSim/src/mixed_model.py:24: RuntimeWarning: overflow encountered in power
  wei_cdf = 1 - np.exp(-1 * np.power(x / l, k))

How will this effect the read profiling step?

Thanks,
Natasha

**Comment by cheny19** [comment]
Hi Natasha,

Sorry about the late reply. No, it will not affect the profiling step.

Thanks,
Chen
