### ISSUE TITLE
Does NanoSim work with PacBio?

### ISSUE THREAD

**Issue by cytham** [bcgsc/NanoSim#75]
I know NanoSim is a ONT read simulator, but can it be used to analyse and simulate PacBio reads?

Thanks

**Comment by cheny19** [comment]
Hi @cytham ,

Thank you for your interest in using NanoSim. You can definitely use NanoSim to analyze PacBio reads, and it will give you information about read lengths of aligned reads / unaligned reads, alignment ratio, error rates, etc. 

We haven't tried to use NanoSim to simulate PacBio reads, and their reads may have different features specific to their platform, so NanoSim may not work as well on them as the ONT reads. But it doesn't hurt to give it a shot. The read length distribution and error rates will be maintained well for sure.

Thanks,
Chen

**Comment by cytham** [comment]
Hi Chen,

Thanks for replying. 

I tried genome analysis on PacBio FASTA but got stuck at the "Insertion fitting start" stage for more than a day. Attached is the printed log. I also tried with the --no_model_fit option and it finished successfully and quickly, but I'm not sure what this setting will do. Please help.

Thanks
cy
[nanosim_pacbio_analysis_stuck.txt](https://github.com/bcgsc/NanoSim/files/4011789/nanosim_pacbio_analysis_stuck.txt)

**Comment by cheny19** [comment]
Hi @cytham,

Sorry for the late reply. It seems like our pre-defined mixture model doesn't work great with PacBio data, because of the warning `WARNING! Mismatch parameters may not be optimal!`. But the long runtime may only because you have more than 2 million sequences. 
I'm wondering did you give it another shot and did it finish eventually?

Thanks,
Chen

**Comment by cytham** [comment]
Hi @cheny19 ,

I tested NanoSim with about 500k pacbio reads sometime back and I think the analysis still got stuck and didn't finish. I would suggest you trying it out for yourself. I used the HG002 pacbio data from GIAB.

However, I am currently not looking into solving this issue and have resorted to another simulator for pacbio reads.

Thanks for your help and I will close this issue.

Best,
cy
