### ISSUE TITLE
 processing

### ISSUE THREAD

**Issue by chenyonx** [bcgsc/NanoSim#79]
Hello, I would like to ask why only the middle part of the processing, thank you

**Comment by cheny19** [comment]
Could you elaborate your question?

**Comment by chenyonx** [comment]
Excuse me, I would like to ask why the substitution errors in the simulation are high

**Comment by cheny19** [comment]
The substitution errors are simulated based on empirical reads. It should be as high as those in experimental data.

**Comment by chenyonx** [comment]
But the substitution errors I simulated on the read side were higher than the substitution errors in the profiles file. Have you ever encountered this?

**Comment by chenyonx** [comment]
[simulator_mis.txt](https://github.com/bcgsc/NanoSim/files/4538263/simulator_mis.txt)
[original_mis.txt](https://github.com/bcgsc/NanoSim/files/4538265/original_mis.txt)
This is the comparison between the original and the simulation, please have a look, thank you

**Comment by cheny19** [comment]
It looks like the substitution error is slightly higher than the original ones for long stretches of mismatch, but not by too much. This is probably due to the statistically modelling and alignment.
