### ISSUE TITLE
If the average read length is very similar to your reference length then nanosim goes into an endless loop while trying to get a read to simulate

### ISSUE THREAD

**Issue by psarkozy** [bcgsc/NanoSim#8]
E.g. full-length amplicon sequencing

**Comment by JustinChu** [comment]
Sorry for the late reply,

This can be prevented by using the `--max_len` option, set to your amplicon size. However, this is more of a hack, and ideally, you would simulate by training it first on a sequencing experiment with similar properties (sequencing of another library made using fragments of a similar size to the one being simulated).
