### ISSUE TITLE
Missing file in NA12878 dRNA pre-trained model

### ISSUE THREAD

**Issue by fairliereese** [bcgsc/NanoSim#82]
The `human_NA12878_dDNA_Bham1_guppy` directory is missing at least one file to run the simulator, `training_match_markov_model`.
![Screen Shot 2020-06-01 at 1 34 11 PM](https://user-images.githubusercontent.com/21128281/83452088-f1b5ae80-a40c-11ea-9d97-8233067c9ca9.png)

**Comment by cheny19** [comment]
Hi @fairliereese ,

Thanks for reporting that. I'm working on a new release recently and will include the missing files. Stay tuned.

Chen

**Comment by cheny19** [comment]
Added to release v2.6.0 and closing the issue now.
