### ISSUE TITLE
Better descriptions of input file formats

### ISSUE THREAD

**Issue by fairliereese** [bcgsc/NanoSim#83]
I think that many people will find this tool more useful if you provide example file formats for the many types of reference files that you are expecting people to use. For instance, I am trying to simulate transcriptome reads and your README simply says I need to use "a reference transcriptome". I went with the GENCODE transcriptome simply because that's what the rest of the analysis I've been doing uses. However it's incompatible with your tool. For those having difficulty getting things to work, if your error looks like this: 
![Screen Shot 2020-06-02 at 11 19 47 AM](https://user-images.githubusercontent.com/21128281/83555338-fb015280-a4c2-11ea-92a7-cf68a0b27358.png)
it's because the software expects your transcriptome fasta file to look like this: 
![Screen Shot 2020-06-02 at 11 21 16 AM](https://user-images.githubusercontent.com/21128281/83555467-2edc7800-a4c3-11ea-8956-01e7619d451c.png)
With the fasta headers space separated and the first field having the transcript ID.

**Comment by cheny19** [comment]
Sure! I'll update the README in the new release as well!

**Comment by fairliereese** [comment]
Thanks for your responsiveness!

**Comment by cheny19** [comment]
It was not very clear before, now I added to the README that the transcripts name has to be consistent in all the input files. Thanks for the suggestion!
