### ISSUE TITLE
DNA adapter in DRS

### ISSUE THREAD

**Issue by Huanle** [bcgsc/NanoSim#93]
Hi,
How do you deal with sequencing the DNA adapters using the direct RNA sequencing chemistry?
Thanks a lot for developing the simulator, which is very useful.

**Comment by cheny19** [comment]
Hi, 

In our simulation, we don't simulate adapters. We used Porechop processed reads for training, and presumably users will use trimmed reads for downstream analysis as well. 

Thanks,
Chen

**Comment by Huanle** [comment]
Thanks heaps for your explanation @cheny19
