### ISSUE TITLE
Bug: fastq sequence and quality length different

### ISSUE THREAD

**Issue by myhsi** [bcgsc/NanoSim#98]
Hi, I generated some fastq reads using one of your models but it generates files which occasionally contain sequences where the sequence length and the quality length in the fastq file are different. This came up because I was trying to characterize the data with Nanoplot and it threw an error message: 

ValueError: Lengths of sequence and quality values differs for NC-003210_732235_aligned_1432_F_2089_47_1342 (3478 and 3518).
"""

**Comment by kmnip** [comment]
Hi @myhsi ,

We are aware of the bug. It was fixed in commit 3a3dff2 .

Ka Ming

**Comment by myhsi** [comment]
@kmnip, was this pushed to the latest conda package? I encountered the issue while using v2.6.0 installed through conda. Thanks!

**Comment by kmnip** [comment]
No, it isn't because the bug was discovered and fixed after v2.6.0 was released.
We are finalising some changes for a new release soon.

**Comment by eppinglen** [comment]
Hi, I am getting the same error while simulating metagenome reads with version 3.0. 
`Lengths of sequence and quality values differs for NZ-CP031256_4650403;aligned_0_F_17_12723_2 (12753 and 30461).`

**Comment by SaberHQ** [comment]
@cheny19 it seems like that @eppinglen has the same issue with the version 3.0 as well. I am reopening the issue.

**Comment by cheny19** [comment]
@eppinglen @SaberHQ ,

Thanks for reporting this. It's a different bug than the previous one and this only exists in the metagenome simulation. I have fixed this and officially made release 3.0.0. Please let me know if there's any further questions.

Cheers,
Chen

**Comment by eppinglen** [comment]
@cheny19  Thank you for the quick response. It is working fine now.
