### ISSUE TITLE
need more information on the Input files 

### ISSUE THREAD

**Issue by yhg926** [bcgsc/NanoSim#99]
Dear author:
I want to run this command:
./simulator.py transcriptome -rt Mus_musculus.GRCm38.cdna.all.fa -c mouse_cdna -e abundance.tsv -n 5000 --no_model_ir,

would you please provide some information on how to find these files:" Mus_musculus.GRCm38.cdna.all.fa"
and how to create " mouse_cdna" and "abundance.tsv" ? 
Many thanks.

**Comment by kmnip** [comment]
Please consult the README on "transcriptome mode usage":
https://github.com/bcgsc/NanoSim#2-simulation-stage

The `-rt` options specifies the reference transcriptome for the similator. So, the file `Mus_musculus.GRCm38.cdna.all.fa` is a FASTA file containing the transcript sequences to simulate. This file is usually part of the annotation. For example, you can find the mouse reference transcripts on Ensembl here:
ftp://ftp.ensembl.org/pub/release-101/fasta/mus_musculus/cdna/Mus_musculus.GRCm38.cdna.all.fa.gz

The `-c` options specifies the prefix for the trained model. You can either train your own models (i.e. "characterization stage") or use the pre-trained models for human and mouse here:
https://github.com/bcgsc/NanoSim/tree/master/pre-trained_models

The `abundance.csv` file should contain the isoform expression levels for NanoSim to simulate. It can be generated from the characterization stage or the expression values can be completely artificial.

Hope that helps!
Ka Ming
